algo: duelingq
envparameters:
  action_continuous: false
  action_space: 3
  n_player: 1
  obs_continuous: true
  obs_space: 2
  scenario: classic_MountainCar-v0
hyperparameters:
  batch_size: 64
  buffer_capacity: 256
  c_lr: 0.005
  epsilon: 0.5
  epsilon_end: 0.05
  gamma: 0.99
  given_net: false
  hidden_size: 100
  network: critic
  target_replace: 100
  marl: false
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  learn_freq: 1
  learn_terminal: False
  max_episodes: 1000
  render: false
  save_interval: 50
