algo: ppo
envparameters:
  action_continuous: false
  action_space: 2
  n_player: 1
  obs_continuous: true
  obs_space: 4
  scenario: classic_CartPole-v0
hyperparameters:
  a_lr: 0.0005
  batch_size: 64
  buffer_capacity: 200
  c_lr: 0.0005
  clip_param: 0.2
  gamma: 0.99
  hidden_size: 64
  num_hidden_layer: 1
  learn_terminal: true
  marl: false
  max_grad_norm: 0.5
  update_freq: 10
  use_network: true
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 20
  max_episodes: 1000
  render: false
  save_interval: 100
