algo: sarsa
envparameters:
  action_continuous: false
  action_space: 4
  n_player: 1
  obs_continuous: true
  obs_space: 108
  scenario: gridworld
hyperparameters:
  buffer_capacity: 1
  epsilon: 0.2
  epsilon_end: 0.01
  gamma: 0.9
  given_net: false
  hidden_size: 100
  lr: 0.1
  marl: false
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  learn_freq: 1
  learn_terminal: false
  max_episodes: 1000
  render: false
  save_interval: 1000
