algo: sac
envparameters:
  action_continuous: true
  action_space: 1
  n_player: 1
  obs_continuous: true
  obs_space: 3
  scenario: classic_Pendulum-v0
hyperparameters:
  batch_size: 64
  buffer_capacity: 2048
  c_lr: 0.001
  a_lr: 0.001
  alpha_lr: 0.001
  alpha: 0.2
  epsilon: 0.5
  epsilon_end: 0.05
  gamma: 0.99
  hidden_size: 64
  num_hid_layer: 1
  target_replace: 20
  network: critic
  policy_type: gaussian
  clip_param: 0.2
  target_entropy_ratio: 0.7
  tau: 0.001
  tune_entropy: true
  marl: false
  learn_freq: 1
  learn_terminal: false
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 20
  max_episodes: 1000
  render: false
  save_interval: 100
  use_cuda: false
